<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Tetris</title>
  <link rel="stylesheet" href="style.css">
</head>
<body>
  <h1>Tetris</h1>

  <!-- Start Menu -->
  <div id="startMenu">
    <p>Select Speed:</p>
    <select id="levelSelect">
      <option value="1000">Easy</option>
      <option value="500">Medium</option>
      <option value="200">Hard</option>
    </select><br>
    <button onclick="startGame()">Start Game</button>
  </div>

  <!-- Game Area -->
  <div id="game">
    <p>Score: <span id="score">0</span></p>
    <canvas id="tetris" width="240" height="400"></canvas>
    <div>
      <button onclick="move(-1)">◀</button>
      <button onclick="rotate()">⟳</button>
      <button onclick="move(1)">▶</button>
      <button onclick="drop()">▼</button>
    </div>
  </div>

  <script src="script.js"></script>
</body>
</html>
